apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name }}-get-secrets
  namespace: {{ .Chart.Name }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-get-secrets
  namespace: {{ .Chart.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Chart.Name }}-get-secrets
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Chart.Name }}
